#!/usr/bin/env python3
import os

commands = {
    "uu-arch",
    "uu-b2sum",
    "uu-base32",
    "uu-base64",
    "uu-basename",
    "uu-basenc",
    "uu-cat",
    "uu-chgrp",
    "uu-chmod",
    "uu-chown",
    "uu-chroot",
    "uu-cksum",
    "uu-comm",
    "uu-coreutils",
    "uu-cp",
    "uu-csplit",
    "uu-cut",
    "uu-date",
    "uu-dd",
    "uu-df",
    "uu-dir",
    "uu-dircolors",
    "uu-dirname",
    "uu-du",
    "uu-echo",
    "uu-env",
    "uu-expand",
    "uu-expr",
    "uu-factor",
    "uu-false",
    "uu-fmt",
    "uu-fold",
    "uu-groups",
    "uu-hashsum",
    "uu-head",
    "uu-hostname",
    "uu-id",
    "uu-install",
    "uu-join",
    "uu-kill",
    "uu-link",
    "uu-ln",
    "uu-logname",
    "uu-ls",
    "uu-md5sum",
    "uu-mkdir",
    "uu-mkfifo",
    "uu-mknod",
    "uu-mktemp",
    "uu-more",
    "uu-mv",
    "uu-nice",
    "uu-nl",
    "uu-nohup",
    "uu-nproc",
    "uu-numfmt",
    "uu-od",
    "uu-paste",
    "uu-pathchk",
    "uu-pr",
    "uu-printenv",
    "uu-printf",
    "uu-ptx",
    "uu-pwd",
    "uu-readlink",
    "uu-realpath",
    "uu-rm",
    "uu-rmdir",
    "uu-seq",
    "uu-sha1sum",
    "uu-sha224sum",
    "uu-sha256sum",
    "uu-sha384sum",
    "uu-sha512sum",
    "uu-shred",
    "uu-shuf",
    "uu-sleep",
    "uu-sort",
    "uu-split",
    "uu-stat",
    "uu-stdbuf",
    "uu-stty",
    "uu-sum",
    "uu-sync",
    "uu-tac",
    "uu-tail",
    "uu-tee",
    "uu-test",
    "uu-timeout",
    "uu-touch",
    "uu-tr",
    "uu-true",
    "uu-truncate",
    "uu-tsort",
    "uu-tty",
    "uu-uname",
    "uu-unexpand",
    "uu-uniq",
    "uu-unlink",
    "uu-vdir",
    "uu-wc",
    "uu-whoami",
    "uu-yes",
}

# Path to ~/.bash_aliases
aliases_file = os.path.expanduser("~/.bash.d/.ba")
cc = []
with open(aliases_file) as f:
    lines = f.readlines()
    for line in lines:
        if not any(c in line for c in commands):
            cc.append(line)

with open(".ba", "w") as fo:
    for k in cc:
        fo.write(k)
